import {state,can,put} from "./store.js";import {esc,project} from "./forms.js";import {analyze,cfg} from "./insights.js";
const n=x=>Math.round(x).toLocaleString("en-US"),pc=x=>x==null?"—":Math.round(x)+"%";
const SC={r:["#c4573f","حرج"],a:["#d79b2b","انتباه"],g:["#2e8b6e","سليم"],n:["#9aa7b4","لا بيانات"]},SV={h:SC.r[0],m:SC.a[0],l:"#9aa7b4"};
const dot=c=>`<span style="display:inline-block;width:10px;height:10px;border-radius:50%;background:${c};margin-left:6px"></span>`;
const card=(a,g)=>`<div class="al" style="border-right:4px solid ${SV[a.sev]}"><b>${esc(a.t)}</b>${a.pn?` <span class="mut">— ${esc(a.pn)}</span>`:""}<p>${esc(a.why)}</p><details><summary>ماذا أفعل؟</summary><div style="white-space:pre-line">${esc(g[a.g]||"")}</div></details>${can("receipt")?`<div class="row" style="margin-top:8px"><button class="alt" data-ack="${esc(a.k)}" data-s="done">تمت المعالجة</button><button class="alt" data-ack="${esc(a.k)}" data-s="snooze">تأجيل 7 أيام</button></div>`:""}</div>`;
const acks=el=>el.querySelectorAll("[data-ack]").forEach(b=>b.onclick=()=>{const k=b.dataset.ack,s=b.dataset.s;put("alerts",k.replace(/[\/\s]/g,"_"),{key:k,status:s,until:s==="snooze"?new Date(Date.now()+7*864e5).toISOString().slice(0,10):null})});
let ch;
export function overview(el,sel,pick){const {M,A}=analyze(),c=cfg(),mgr=state.role!=="entry";ch?.destroy();
  const m0=sel&&M.find(x=>x.p.id===sel);if(m0)return detail(el,m0,A.filter(a=>a.pid===sel),c,pick);
  const T=M.reduce((s,m)=>({sp:s.sp+m.spent,rv:s.rv+m.rev}),{sp:0,rv:0}),cnt=k=>M.filter(m=>m.st===k).length;
  el.innerHTML=`<div class="cards">${mgr?`<div class="c"><small>الإيرادات</small><b>${n(T.rv)}</b></div>`:""}<div class="c"><small>المصاريف</small><b>${n(T.sp)}</b></div>${mgr?`<div class="c"><small>صافي الربح</small><b class="${T.rv-T.sp>=0?"pos":"neg"}">${n(T.rv-T.sp)}</b></div>`:""}<div class="c"><small>مشاريع حرجة / انتباه</small><b><span class="neg">${cnt("r")}</span> / <span style="color:#d79b2b">${cnt("a")}</span></b></div></div>
<div class="box"><b>يحتاج قرارك (${A.length})</b>${A.slice(0,8).map(a=>card(a,c.guide)).join("")||'<p class="mut">لا توجد تنبيهات. الوضع سليم بحسب الحدود الحالية.</p>'}${A.length>8?`<p class="mut">و${A.length-8} تنبيهات أخرى أقل خطورة، تظهر داخل صفحة كل مشروع.</p>`:""}</div>
<div class="box"><b>صحة المشاريع</b> <span class="mut">(اضغط على مشروع للتفاصيل)</span><table><tr><th>المشروع</th><th>العقد</th><th>المفوتر</th><th>المصروف</th><th>استهلاك الميزانية</th><th>الإنجاز</th><th>الهامش</th><th>الحالة</th></tr>${M.map(m=>`<tr class="pj" data-pj="${m.p.id}"><td><b>${esc(m.p.name)}</b></td><td>${m.cv?n(m.cv):"—"}</td><td>${mgr?n(m.rev):"—"}</td><td>${n(m.spent)}</td><td>${m.use==null?"—":`<div style="display:flex;gap:8px;align-items:center"><div class="bar" style="flex:1"><i style="width:${Math.min(100,m.use)}%;background:${m.use>100?SC.r[0]:m.use>c.th.budget?SC.a[0]:SC.g[0]}"></i></div>${Math.round(m.use)}%</div>`}</td><td>${pc(m.pr||null)}</td><td>${mgr?pc(m.mg):"—"}</td><td>${dot(SC[m.st][0])}${SC[m.st][1]}</td></tr>`).join("")||"<tr><td colspan=8>أضف مشروعاً بزر +</td></tr>"}</table></div>`;
  el.querySelectorAll("[data-pj]").forEach(r=>r.onclick=()=>pick(r.dataset.pj));acks(el)}
function detail(el,m,al,c,pick){const p=m.p,bc=p.budgets||{},ex=state.expenses.filter(x=>x.projectId===p.id);
  const rows=[...new Set([...Object.keys(bc),...ex.map(x=>x.category)])].map(k=>{const s=ex.filter(x=>x.category===k).reduce((a,x)=>a+x.amount-(x.vat||0),0),b=+bc[k]||0;return{k,s,b,u:b?s/b*100:null}}).sort((a,b)=>b.s-a.s);
  el.innerHTML=`<button class="alt" id="bk" style="margin-bottom:10px">← كل المشاريع</button><div class="row" style="margin-bottom:10px;align-items:center"><h3 style="margin:0">${esc(p.name)} ${dot(SC[m.st][0])}<small>${SC[m.st][1]}</small></h3>${can("edit")?`<button id="ed" class="alt" style="flex:0 0 auto">تعديل المشروع</button>`:""}${can("receipt")||can("edit")?`<button id="pg" class="alt" style="flex:0 0 auto">تحديث الإنجاز</button>`:""}</div>
<div class="cards"><div class="c"><small>الإنجاز</small><b>${pc(m.pr||null)}</b></div><div class="c"><small>المصروف / الميزانية</small><b>${n(m.spent)} / ${m.bt?n(m.bt):"—"}</b></div><div class="c"><small>التكلفة المتوقعة عند الإتمام</small><b>${m.eac?n(m.eac):"—"}</b></div><div class="c"><small>كفاءة التكلفة (CPI)</small><b class="${m.cpi&&m.cpi<.95?"neg":""}">${m.cpi?m.cpi.toFixed(2):"—"}</b></div><div class="c"><small>الهامش</small><b>${state.role!=="entry"?pc(m.mg):"—"}</b></div></div>
<div class="box"><b>التنبيهات والإرشاد</b>${al.map(a=>card(a,c.guide)).join("")||'<p class="mut">لا تنبيهات لهذا المشروع.</p>'}</div>
<div class="box"><b>البنود: التقدير مقابل الفعلي</b><div class="cv"><canvas id="cb"></canvas></div><table><tr><th>البند</th><th>التقدير</th><th>الفعلي</th><th>الاستهلاك</th><th>الفرق</th></tr>${rows.map(r=>`<tr><td>${esc(r.k)}</td><td>${r.b?n(r.b):"—"}</td><td>${n(r.s)}</td><td>${r.u==null?"بلا تقدير":`<span style="color:${r.u>100?SC.r[0]:r.u>c.th.budget?SC.a[0]:SC.g[0]}">${Math.round(r.u)}%</span>`}</td><td>${r.b?`<span class="${r.s>r.b?"neg":"pos"}">${r.s>r.b?"+":"−"}${n(Math.abs(r.s-r.b))}</span>`:"—"}</td></tr>`).join("")}</table></div>`;
  if(rows.length)ch=new Chart(el.querySelector("#cb"),{type:"bar",data:{labels:rows.map(r=>r.k),datasets:[{label:"التقدير",data:rows.map(r=>r.b),backgroundColor:"#b8c6d4",borderRadius:4,maxBarThickness:30},{label:"الفعلي",data:rows.map(r=>r.s),backgroundColor:rows.map(r=>r.u>100?"#c4573f":"#2f6f9f"),borderRadius:4,maxBarThickness:30}]},options:{maintainAspectRatio:false,plugins:{legend:{position:"bottom",rtl:true,labels:{usePointStyle:true}}},scales:{x:{grid:{display:false}},y:{beginAtZero:true,grid:{color:"#e6ebf0"}}}}});
  el.querySelector("#bk").onclick=()=>pick("");const ed=el.querySelector("#ed");if(ed)ed.onclick=()=>project(p);
  const pg=el.querySelector("#pg");if(pg)pg.onclick=()=>{const v=prompt("نسبة الإنجاز الحالية %",p.progress||0);if(v!==null&&!isNaN(v))put("projects",p.id,{progress:Math.min(100,Math.max(0,+v))})};acks(el)}
